### PR TITLE
Sorted json files 2024-02-22

### PR DESCRIPTION
**Pull request by ibrahim-kabir**
## Summary of changes
I have investigated why the scores are poor and below I have listed the reasons. The records have been renamed to sorted_date. I have added the field skip and reason to the JSON files listed below.

## Duplicates
It should be noted that questions may be duplicated. Therefore, if a flawed question appears more than once, it will lower the score.

| 📄 File               | 💬 Question  | 
|--|--|
|qna_2024-02-22_81.json, qna_2024-02-22_40.json, qna_2024-02-22_93.json, qna_2024-02-22_48.json, qna_2024-02-22_83.json, qna_2024-02-22_20.json,  qna_2024-02-22_54.json, qna_2024-02-22_58.json, qna_2024-02-22_62.json, qna_2024-02-22_89.json, qna_2024-02-22_47.json, qna_2024-02-22_38.json| Comment obtenir le rapport complet? Quelle est la version intégrale du rapport disponible sur demande?|
| qna_2024-02-22_88.json,qna_2024-02-22_96.json, qna_2024-02-22_59.json  | What is the purpose of the product photos?|
| qna_2024-02-22_34.json, qna_2024-02-22_99.json, qna_2024-02-22_13.json, qna_2024-02-22_65.json, qna_2024-02-22_56.json, qna_2024-02-22_75.json, qna_2024-02-22_36.json, qna_2024-02-22_25.json, qna_2024-02-22_43.json, qna_2024-02-22_17.json, qna_2024-02-22_53.json, qna_2024-02-22_91.json, qna_2024-02-22_84.json, qna_2024-02-22_79.json,qna_2024-02-22_3.json, qna_2024-02-22_32.json,qna_2024-02-22_27.json,qna_2024-02-22_66.json, qna_2024-02-22_39.json, qna_2024-02-22_63.json, qna_2024-02-22_74.json, qna_2024-02-22_85.json, qna_2024-02-22_42.json, qna_2024-02-22_34.json, qna_2024-02-22_2.json, qna_2024-02-22_52.json, qna_2024-02-22_100.json, qna_2024-02-22_64.json, qna_2024-02-22_71.json, qna_2024-02-22_41.json, qna_2024-02-22_26.json, qna_2024-02-22_57.json, qna_2024-02-22_29.json, qna_2024-02-22_95.json, qna_2024-02-22_28.json, qna_2024-02-22_21.json, qna_2024-02-22_97.json, qna_2024-02-22_61.json, qna_2024-02-22_10.json| Comment ouvrir un formulaire téléchargé ? Comment ouvrir un formulaire dans Google Chrome ? Comment imprimer des formulaires PDF ?What are some tips for completing dynamic (PDF-XFA) forms?Comment envoyer des formulaires en format PDF par courriel?Comment signer un formulaire en utilisant une identification numérique?Comment ouvrir un formulaire?How should I print PDF forms?Comment signer un formulaire en utilisant une identification numérique?How can I send PDF forms by email? How can I sign a form digitally?| 
|qna_2024-02-22_4.json, qna_2024-02-22_69.json, qna_2024-02-22_24.json, qna_2024-02-22_33.json|Comment mettre en surbrillance les champs à remplir dans Adobe Reader ?|
|qna_2024-02-22_50.json |What are some tips for completing dynamic (PDF-XFA) forms?|
|qna_2024-02-22_77.json, qna_2024-02-22_8.json|Quels sont les contacts pour les demandes de renseignements du public?|

## Other Vague Questions
Some questions are overly vague or general, which hinders the script from generating a satisfactory score.

| 📄 File               | 💬 Question  |  ⏫ Better question form |
|--|--|--|
| qna_2024-02-22_89.json | [Quelle est la version intégrale du rapport disponible sur demande?](https://inspection.canada.ca/salubrite-alimentaire-pour-l-industrie/chimie-et-microbiologie-alimentaires/bulletin-d-enquete-et-rapports-d-analyse-sur-la-sa/bacteries-pathogenes-et-e-coli-de-type-generique-d/fra/1430919291153/1430919291669)' | Quelle est la version intégrale du rapport disponible sur demande concernant l'étude ciblée de 2010-2011 sur la présence de bactéries pathogènes dans les légumes-feuilles? (Medium score)|
| qna_2024-02-22_70.json | [Who is this document for?](https://inspection.canada.ca/animal-health/terrestrial-animals/biosecurity/standards-and-principles/equine-sector/eng/1460662612042/1460662650577) | For whom is the National Farm and Facility Level Biosecurity Standard for the Equine Sector designed (100%) |
| qna_2024-02-22_49.json | [What does the term 'Schedule' refer to?](https://inspection.canada.ca/eng/1666975595834/1666975596413)' |'Schedule' within the context of the avian influenza response in the Primary Control Zone (Medium score)|
| qna_2024-02-22_26.json | [How do I open a form?](https://inspection.canada.ca/about-cfia/find-a-form/form-cfia-acia-1317/eng/1426264529452/1426264530124) | How can I access and open the Application for Seed Potato Crop Inspection – Grower's Declaration form ? (100%)|
| qna_2024-02-22_23.json | [What does the schedule include for poultry?](https://inspection.canada.ca/eng/1677946819050/1677946819581)|Quelles informations spécifiques concernant les volailles sont incluses dans le calendrier du document sur la zone de contrôle primaire en Nouvelle-Écosse? (100%)|
| qna_2024-02-22_72.json | [What triggered this recall?](https://inspection.canada.ca/food-recall-warnings-and-allergy-alerts/2019-10-15/eng/1571192117978/1571192124399)
| qna_2024-02-22_15.json | [What does paragraph 19(1) of the Regulation state?](https://inspection.canada.ca/sante-des-animaux/aliments-du-betail/consultations/normes-relatives-aux-contaminants-aflatoxines-deox/sommaire-des-consultations/fra/1544482075311/1544482140088)|Qu'est-ce que le Règlement de 1983 sur les aliments du bétail stipule au paragraphe 19(1) ? (High score)|
| qna_2024-02-22_68.json | [What subjects are not covered in this document?](https://inspection.canada.ca/animal-health/humane-transport/health-of-animals-regulations-part-xii/eng/1582126008181/1582126616914)||
| qna_2024-02-22_44.json | [Quels sont les détails du rappel?](https://inspection.canada.ca/avertissements/2021-10-15/fra/1634327751769/1634327759471)||
| qna_2024-02-22_5.json| [What does the schedule include for poultry?](https://inspection.canada.ca/eng/1664053525638/1664053526029)|
## Web page not found
Some web links to questions cannot be found, which is strange because the questions appear to have been generated before becoming untraceable.

| 📄 File               | 💬 Question  | 
|--|--|
| qna_2024-02-22_76.json | [What is the requirement for operators and license holders regarding complaints?](https://inspection.canada.ca/about-cfia/transparency/consultations-and-engagement/supporting-compliance/discussion-paper/eng/1402209258312/1402209557237)
| qna_2024-02-22_90.json | [What is the topic of Partie 14?](https://inspection.canada.ca/a-propos-de-l-acia/transparence/rapports-de-gestion/rapports-au-parlement/2019-a-2020/exercice/fra/1601562620503/1601562620887)

## Unknown reasons
Some questions have a low score for an unknown reason that has yet to be determined.

| 📄 File               | 💬 Question  |  🔄 Other question form |
|--|--|--|
|qna_2024-02-22_1.json	 | [Qu'est-ce que le Règlement sur la salubrité des aliments au Canada (RSAC) ?](https://inspection.canada.ca/a-propos-de-l-acia/lois-et-reglements/plan-prospectif-de-la-reglementation/initiatives-en-matiere-de-politiques-et-de-program/fra/1612284909727/1612284909961)| Quelles sont les normes internationales de salubrité des aliments appliquées par le Règlement sur la salubrité des aliments au Canada (RSAC) entré en vigueur le 15 janvier 2019, et comment ce règlement harmonise-t-il les exigences pour les produits alimentaires au Canada ? (No score)|

### CODE REVIEW

**Review by k-allagbe — COMMENTED** [review]
Is the `skip` field manually added? Do we want to automate it?

**Comment by ibrahim-kabir** [comment]
> Is the `skip` field manually added? Do we want to automate it?

Good question, since we want to review each question by a human, it is manually added.

**Review by rngadam — APPROVED** [review]
can we open a follow issue to ensure that the process generating .json writes a final newline at the end of the file? all the json here are non-conforming

**Comment by ibrahim-kabir** [comment]
> can we open a follow issue to ensure that the process generating .json writes a final newline at the end of the file? all the json here are non-conforming

Issue created here ai-cfia/api-test#13

**Comment by ibrahim-kabir** [comment]
@k-allagbe, @cfiaGeetika, 

I cannot find an explanation for why this question is giving a null score: [What is the Canada Food Safety Regulations (CFIA)?](https://inspection.canada.ca/a-propos-de-l-acia/lois-et-reglements/plan-prospectif-de-la-reglementation/initiatives-en-matiere-de-politiques-et-de-program/fra/1612284909727/1612284909961). Both Bing and Bing Filtered provide the same result in French or English: image

**Comment by rngadam** [comment]
> I cannot find an explanation for why this question is giving a null score: [What is the Canada Food Safety Regulations (CFIA)?](https://inspection.canada.ca/a-propos-de-l-acia/lois-et-reglements/plan-prospectif-de-la-reglementation/initiatives-en-matiere-de-politiques-et-de-program/fra/1612284909727/1612284909961). Both Bing and Bing Filtered provide the same result in French or English:

file a separate issue for each question so we can deepen the investigation into why?

**Pull request merged**
